name: Docker

on: [push]

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: publish-topics-init
        uses: versicherungskammer/multi-platform-docker-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image-name: topics-init
          auto-tags: branch-name latest-if-main commit-hash
          path: topics-init
          docker-file: topics-init/Dockerfile

      - name: publish-mock-facility-management
        uses: versicherungskammer/multi-platform-docker-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image-name: mock-facility-management
          auto-tags: branch-name latest-if-main commit-hash
          path: mock-facility-management
          docker-file: mock-facility-management/Dockerfile

#      - name: publish-mock-human-resources
#        uses: versicherungskammer/multi-platform-docker-action@v1
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          image-name: mock-human-resources
#          auto-tags: branch-name latest-if-main commit-hash
#          path: mock-human-resources
#          docker-file: mock-human-resources/Dockerfile
